### ISSUE TITLE
NetworkResult 관련 질문드립니다.

### ISSUE THREAD

**Issue by Kick-snare** [Team-Planz/Planz-Android#10]
안녕하세요? YAPP 이랑은 전혀 관련도 없는 그냥 부산살면서 안드로이드 공부하는 학생입니다. 

레퍼런스를 찾아다니다가 어찌저찌 해서 여기까지 오게 되었는데 코드가 잘 짜져있는 듯하여 참고하려고 살펴보던 중 입니다.
그러던 중 궁금한 점이 생겨서 이슈로 질문드립니다.

## ISSUE

API 요청을 핸들링하기 위해서 Retrofit 응답 DTO 객체를 `handleApi.kt`에서 익셉션으로 필터링해서 `NetworkResult`로 감싸더군요. 그리고 wrapping된 채로 usecase를 거쳐서 viewModel에서 NetworkResult의 onSuccess나 onError와 같은 확장함수로 처리하는 것을 확인했습니다.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/46425142/218378085-546ddfd3-3e45-4a1e-be70-2170de37761a.png">

메서드 체이닝으로 반환 결과에 따라 처리하니까 간편하고 좋다고 생각해서 따라할까하다가 걸리는 점이 있어 질문드립니다.
domain 계층, presentation 계층도 NetworkResult를 알아야하는데 클린 아키텍처에 위반되는 것이 아닐까요? NetworkResult는 data 단에서만 알고 있어야 하지 않나 싶습니다.

다른 레퍼런스들을 많이 찾아봤는데 비동기 flow로 함수 파라미터로 onError등을 넘겨받아 funtional하게 처리하는 방법등이 있었습니다. [참고](https://github.com/skydoves/Pokedex/blob/main/core-data/src/main/kotlin/com/skydoves/core/data/repository/DetailRepositoryImpl.kt) 하지만 제가 하고 싶은건 단발성 데이터라 flow를 사용하지 않으면서도 view에서 결과에 따라 error 처리를 하고 싶은 마음인데 domain에서 또 다시 wrapping을 해야할지(보일러 플레이트가 늘어남), 에러 시 그냥 null data를 보내야할지(부정확함?) 고민입니다.

이걸 인지하고 이렇게 사용하신건지, 그리고 개선방법을 생각하신게 있다면 어떻게 하면 좋을지 Planz 개발진 분들의 의견이 궁금합니다. 감사합니다!!

**Comment by KwonDae** [comment]
안녕하세요~
먼저 플랜드 안드로이드에 관심갖고 질문주셔서 감사합니다 ㅎㅎ

`NetworkResult.kt`는 domain 모듈의 순수 코틀린으로 이루어진 파일입니다. 이를 presentation, data 모듈에서 참조해서 사용중인 구조이구요. [참고](https://github.com/Team-Planz/Planz-Android/blob/develop/domain/src/main/java/com/yapp/growth/domain/NetworkResult.kt)

presentation -> domain <- data 의존성을 갖기에 안드로이드 클린 아키텍처에서 권장하는 의존성 관계에서 벗어나지 않는다고 생각하여 위처럼 구조를 설계했습니다.
실제로 presentation, data 모듈에서는 domain 모듈의 model 과 같은 데이터를 참조하여 데이터를 송수신하고 view 를 업데이트를 하거나 data 를 요청하니까요

혹시 이해가 안가시는 부분이 있으시다면 편하게 말씀해주세요 감사합니다.

**Comment by Kick-snare** [comment]
답변주셔서 감사합니다. domain에서는 아래 계층인 data를 몰라야한다고 생각해서 질문드렸는데 지금 생각해보니까 말씀대로 NetworkResult 자체는 의존성이 없는 것 같네요! 이해했습니다.

질문 한가지 더 드려도 될까요? 그렇다면 응답 결과에서 exeception에 따라 handleApi로 변환하는것 같은데요, 그래서 dataSource애서 handleApi를 매번 api 함수에 감싸고 있습니다.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/46425142/218384701-c7112fbc-9d47-4e31-94a8-3089022b922c.png">

이러한 보일러플레이트 코드를 해결하기 위해 아예 custom Retrofit CallAdapter를 도입하는건 어떻게 생각하시나요? [참고](https://proandroiddev.com/modeling-retrofit-responses-with-sealed-classes-and-coroutines-9d6302077dfe)
skydove님의 글에서는 문제를 이런식으로 풀어내어서 어떠한 장단점이 있을까 고민중입니다.

**Comment by KwonDae** [comment]
좋은 참고자료를 첨부해주셔서 감사합니다.

> Everything works fine, but you still need to write the handleApi function repeatedly for each network request. It means not only the data layer has a dependency on the handleApi, but also the responsibility of handling the API responses.

> So, how do we improve this process? One of the best ways is by building a custom [Retrofit CallAdapter](https://square.github.io/retrofit/2.x/retrofit/retrofit2/CallAdapter.html), which allows you to delegate call responses;

Custom Retrofit CallAdapter 를 적용한다면 DataSource 에서 매번 handleApi 를 필요로 하는 상황(보일러 플레이트를 야기)을 생략할 수 있겠네요. 좋은 의견 감사합니다 :)

**Comment by hoyahozz** [comment]
좋은 자료 감사드립니다 :)

초기 세팅 시 별도 클래스를 생성한다는 점 외에는 큰 단점이 보이지 않네요!

팀원 모두가 `Custom Retrofit CallAdapter` 에 대해 인지하고 사용한다면, 말씀해주신 것처럼 보일러 플레이트 코드를 줄일 수 있어 매우 좋은 솔루션인 것 같습니다~

**Comment by Kick-snare** [comment]
상황에 따라 다르겠지만 저는 Retrofit `Response`를 `handleApi`를 통해 Kotlin 1.3부터 내장된 `Result<T>` 로 변환하여 넘겨주고 있습니다. [참고1](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) [참고2](https://toss.tech/article/kotlin-result) CallApdapter를 사용하는 것은 말씀 해주신 것 처럼 중복 제거의 효과가 있을 것 같긴하지만 혼자 진행하면서 중요도에 비해 학습/적용에 많은 노력이 들어가는 듯 하여 포기했습니다.

두 분 @KwonDae @hoyahozz  모두 의견 정말 감사합니다! 제 고민에 많은 도움이 되었습니다. 
복 많이 받으세요 🙇
